# 01. NumPy Basics

### Working with NumPy - for Mathematical Operations

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
# Create Zeros, Ones, Custom array
a = np.zeros((3,5))
print(a)

b = np.ones((2,3))
print(b)

# Array of some constants
c = np.full((3,4),6)
print(c)

# Identity Matrix - Size/Square Matrix
d = np.eye(4)
print(d)

# Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.33909203 0.85253526 0.922366  ]
 [0.09517402 0.38197967 0.54006109]]


In [7]:
print(randomMatrix[:,1])

[0.85253526 0.38197967]


In [10]:
randomMatrix[1,1:] = 1 # Slicing
print(randomMatrix)

[[0.33909203 0.85253526 0.922366  ]
 [0.09517402 1.         1.        ]]


In [15]:
# Set some rows and columns with any values
z = np.zeros((3,3))
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)
print(z.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]
float64


In [16]:
# Datatypes
z = np.zeros((3,3),dtype=np.int64)
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]
int64


In [20]:
# Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Element-wise Addition
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [23]:
# Matrix Multiplication / Dot Products
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [24]:
# Multiplication(Dot Product) of Vectors - Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [25]:
print(a)

[1 2 3 4]


In [26]:
print(sum(a))

10


In [29]:
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [30]:
print(np.sum(x,axis=0))

[4 6]


In [31]:
print(np.sum(x,axis=1))

[3 7]


In [49]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

In [50]:
# Stacking of arrays
print(a)
b = b + 4
print(b)

[1 2 3 4]
[5 6 7 8]


In [51]:
np.stack((a,b),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
a = np.stack((a,b),axis=0)
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
# Reshape a NumPy Array
print(a)
a = a.reshape((4,2))
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
a = a.reshape((8,1))
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [55]:
a = a.reshape((8,))
print(a)

[1 2 3 4 5 6 7 8]


In [56]:
a = a.reshape((4,-1))
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
a = a.reshape((-1,4))
print(a)

[[1 2 3 4]
 [5 6 7 8]]


# 02. Random Generators NumPy

### NumPy Random Module
- rand : Random values in a given shape
- randn : Return a sample (samples) from the standard normal distribution
- randint : Return random integers from low(inclusive) to high(exclusive)
- random : Return random floats in the half open interval [ 0.0,1.0)
- choice : Generates a random sample from a given 1-D arrray
- shuffle : Shuffles the contents of the sequence

In [59]:
a=range(10)
print(a)

range(0, 10)


In [60]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [62]:
np.random.shuffle(a)
print(a)

[12  8 14  7 11  5 10  9 13  6]


In [63]:
print(np.random.rand(2,3))

[[0.5978298  0.28999042 0.70717811]
 [0.59390694 0.16343519 0.16239225]]


In [64]:
# Returns values from standard normal distributions
print(np.random.randn(2,3))

print(np.random.randint(5,10,3))

# Randomly pick one element from an array
print(np.random.choice([1,2,3,4,5,6]))

[[-1.31023265  0.21381717  0.07847555]
 [ 0.74547838  1.47832086  0.64896523]]
[6 8 6]
4


In [65]:
# It will shuffle elements in such a way that first shuffle result will always be same until seed is same
a=np.arange(10)
np.random.seed(9)
np.random.shuffle(a)
print(a)

[8 4 7 2 1 9 3 0 6 5]


# 03. Statistical Computation Using NumPy

### Some More NumPy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [66]:
a=np.array([[1,2,3,4],[5,6,7,0]])
print(np.min(a))

0


In [67]:
a=np.array([[1,2,3,4],[5,6,7,0]])
print(min(a))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [68]:
a=np.array([1,2,3,4])
print(np.min(a))

1


In [69]:
a=np.array([1,2,3,4])
print(min(a))

1


In [70]:
# Specify axis for the direction in the case of multidimensional array
a=np.array([[1,2,3,4],[5,6,7,0]])
print(a)
print(np.max(a,axis=0))
print(np.max(a,axis=1))

[[1 2 3 4]
 [5 6 7 0]]
[5 6 7 4]
[4 7]


In [71]:
b=np.array([1,2,3,4,5])
print(b,end='\n\n')
print(sum(b)/len(b))
print(np.mean(b))
print()
print(a,end='\n\n')
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[1 2 3 4 5]

3.0
3.0

[[1 2 3 4]
 [5 6 7 0]]

[3. 4. 5. 2.]
[2.5 4.5]


In [72]:
c=np.array([1,4,2,5,2,6,2,7])
print(np.median(c))

3.0


In [73]:
# Mean vs Average

# Mean
print(np.mean(c))

# Average is weighted
wt=np.array([1,2,3,4,5,6,7,8])
print(np.average(c,weights=wt))

3.625
4.194444444444445


In [74]:
wt=np.array([1,1,1,1,1,1,1,1])
print(np.average(c,weights=wt))

3.625


In [75]:
#Standard Deviation
u=np.mean(c)
sd=np.sqrt(np.mean(abs(c-u)**2))
print(sd)

#Inbuilt function
print(np.std(c))

2.057759704144291
2.057759704144291


In [76]:
#Variance
print(sd**2)

#Inbuilt function
print(np.var(c))

4.234375000000001
4.234375


<img src='../Images/03. Statistical Computation Using NumPy/Image001.png'/>

# 04. A Visual Introduction - Blog

# 05. Linear Algebra - Matrices and Tensors

<img src='../Images/05. Linear Algebra - Matrices and Tensors/Image001.png'/>

In [1]:
import numpy as np

In [4]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [8]:
# We will represent a vector as a column vector, that is having multiple rows
x = np.array([[4],[5],[8],[9]])
print(x)
print(x.shape)
print(x[0])
print(x[0][0])

x = x.reshape((-1))
print(x)

x = x.reshape((-1,2))
print(x)

[[4]
 [5]
 [8]
 [9]]
(4, 1)
[4]
4
[4 5 8 9]
[[4 5]
 [8 9]]


<img src='../Images/05. Linear Algebra - Matrices and Tensors/Image002.png'/>

In [9]:
# Here X is a Matrix
X = np.array([[4,5,7],[5,10,11],[56,8,7]])
print(X.shape)
print(X)
print(X[1][1])
X[1:,:] = 2
print(X)

(3, 3)
[[ 4  5  7]
 [ 5 10 11]
 [56  8  7]]
10
[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [11]:
# Here T is a Tensor
T = np.array([[[4,5,7],[10,11,13]],[[56,80,90],[9,8,10]]])
print(T.shape)
print(T)

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]


<img src='../Images/05. Linear Algebra - Matrices and Tensors/Image003.png'/>

In [12]:
print(x)
xt = np.transpose(x)
print(xt)

[[4 5]
 [8 9]]
[[4 8]
 [5 9]]


In [15]:
y = x.reshape((-1,1))
print(y)
print(y.shape)
yt = np.transpose(y)
print(yt)
print(yt.shape)

[[4]
 [5]
 [8]
 [9]]
(4, 1)
[[4 5 8 9]]
(1, 4)


# 06. Linear Algebra - Matrix and Hadamard Product

In [17]:
X = np.array([[4,5,6],[10,11,13],[56,80,90]])
Y = np.array([[40,50,70],[100,110,130],[560,800,900]])

In [19]:
print(X.shape)
print(Y.shape)
print(X)
print(Y)

(3, 3)
(3, 3)
[[ 4  5  6]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]


In [20]:
prod = np.dot(X,Y)
print(prod)

[[ 4020  5550  6330]
 [ 8780 12110 13830]
 [60640 83600 95320]]


<img src='../Images/06. Linear Algebra - Matrix and Hadamard Product/Image001.png'/>

<img src='../Images/06. Linear Algebra - Matrix and Hadamard Product/Image002.png'/>

In [21]:
# Different from element wise multiplication
X = np.array([[4,5,6],[10,11,13],[56,80,90]])
Y = np.eye(3)
print(X)
print(Y)

[[ 4  5  6]
 [10 11 13]
 [56 80 90]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
print(X*Y)

[[ 4.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 90.]]


In [25]:
Y = Y*2
Y = Y+1
print(X)
print(Y)

[[ 4  5  6]
 [10 11 13]
 [56 80 90]]
[[7. 3. 3.]
 [3. 7. 3.]
 [3. 3. 7.]]


In [24]:
print(X*Y)

[[ 12.   5.   6.]
 [ 10.  33.  13.]
 [ 56.  80. 270.]]


# 07. Linear Algebra - Norm of a Vector

<img src='../Images/07. Linear Algebra - Norm of a Vector/Image001.png'/>
<img src='../Images/07. Linear Algebra - Norm of a Vector/Image002.png'/>

In [28]:
x=np.array([-5,3,10])
lp2=np.linalg.norm(x)
print(lp2)

11.575836902790225


In [29]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [30]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


# 08. Linear Algebra - Broadcasting

<img src='../Images/08. Linear Algebra - Broadcasting/Image001.png'/>

In [33]:
l=[1,2,3,4]
l=l+1
print(l)
l=l**2
print(l)

TypeError: can only concatenate list (not "int") to list

In [31]:
l=[1,2,3,4]
l=np.array(l)
l=l+1
print(l)
l=l**2
print(l)

[2 3 4 5]
[ 4  9 16 25]


In [32]:
l=[[1,2,3,4],[6,7,8,9]]
l=np.array(l)
print(l+1)
print(l**2)
print(np.sqrt(l))

[[ 2  3  4  5]
 [ 7  8  9 10]]
[[ 1  4  9 16]
 [36 49 64 81]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.44948974 2.64575131 2.82842712 3.        ]]


# 09. Quiz on Basics of Linear Algebra

<img src='../Images/09. Quiz on Basics of Linear Algebra/Image001.png'/>
<img src='../Images/09. Quiz on Basics of Linear Algebra/Image002.png'/>
<img src='../Images/09. Quiz on Basics of Linear Algebra/Image003.png'/>
<img src='../Images/09. Quiz on Basics of Linear Algebra/Image004.png'/>
<img src='../Images/09. Quiz on Basics of Linear Algebra/Image005.png'/>
<img src='../Images/09. Quiz on Basics of Linear Algebra/Image006.png'/>