# 01. Challenge - Air Pollution

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('../Csv Files/Train.csv')
X = df.values[:,:-1]
Y = df.values[:,-1]

In [13]:
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]
(1600, 5)
[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]
(1600,)


In [19]:
X = np.mat(X)
Y = np.mat(Y)

In [20]:
def getWeightMatrix(query_point,X,tau):
    M = X.shape[0]
    W = np.mat(np.eye(M))
    
    for i in range(M):
        xi = X[i]
        x = query_point
        W[i,i] = np.exp(np.dot((xi-x),(xi-x).T)/(-2*tau*tau))
    return W

In [21]:
def predict(X,Y,query_x,tau):
    ones = np.ones((X.shape[0],1))
    X_ = np.hstack((X,ones))
    qx = np.mat([query_x,1])
    W = getWeightMatrix(qx,X_,tau)

    #theta = (X'WX)inv * (X'WY)
    theta = np.linalg.pinv(X_.T*(W*X_))*(X_.T*(W*Y))
    pred = np.dot(qx,theta)
    return theta,pred

In [22]:
theta,pred=predict(X,Y,X[0],0.1)

ValueError: operands could not be broadcast together with shapes (1,6) (1,2) 